# Generated by Django 6.0.3 on 2026-03-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="selected_option",
            field=models.CharField(max_length=1),
        ),
    ]
